[google]
type = "service_account"
project_id = "hybb-utility-system"
private_key_id = "08fee7b6c456f3253cb2b7ac532276f0a4c4056b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCS9G532AzyGjN2
EZtEEd5twWRwt1P8gD4JrTHaiuiwvuPcgBXmHwA767vtPbdCWJU8idOwMxpkKUN5
Z07sw7EcToNjsoc46W4aVOlzoXrNz2S5AsGkmGsMomBY/VZdhS1SDMnaBoYtTBqZ
av0eY3CvvoeX0Y80OIfRXLb+bvffIwxcGsjfHfgl+sFjAMk/kh1nhYzgstGtSZZs
cQ2d27Klwyqcp+WIn5a3WapUhNQg7fVVgTCAwBT4T0tZrDzq7WH9FN4WjDg8Ruuf
xce5PX4k8Ne9wwK3hHOkitxFkxEGBlOWRZCJhM5QWC8uiKhbg6mW5zh3ITuGMwWE
PXg+gheNAgMBAAECggEAC+rkaItYusDoNSYxYXWnhF7KKUqcy4iPlL5Qdt42slq7
ZOmYR7dyOpR1WESIhPS6dD84hSdnzQFRq69L8G81q6DXDpyZqG0PKkss5t03ddML
YpD4KO6EGUaz1JOwT4OaN3dlCULn2mrmaf8KCaRb16IhIe1IlUi+WaVmC7/uZyXe
MVqLA7e5aCIx/tKzrWACqSJPaT6GDHkf6XWc4dnjrgzmB6foqi0YfWRiBsJS8haX
sQrjU5NV0xqIcY+BiXWA7T2xOjbeEeUixZ/DjF6NJ/hEzz+wjBHppKeMHrikghcQ
lZ+a658lokoavdae0ZCoiab3RQryc8HOyvJ3n0SJmwKBgQDF2PlIp0ybKVyETfgt
+2jy1InaTf113ZErbiuiUxPd4oI8FCHBPDJxwG+A3l+VthmGOyyHZbcTIv2EAHv6
FlHm0Mt0ksVHQ2lSGlBGA+o9tuVOUeKn4dotPAPj6XSehjMFzCgLRgMJUWmzSxmA
VjJtxbGsPIGwT/zGoTQgpJdq4wKBgQC+JglgIE8OqGzYVv840Ss+aXsKhgcPWrbV
fqCRHv3dc6VO33PUtNT+HkwjQdXQgRbVu3xjf3a6gkEP/OURStbqszqok/b3W5Ds
+3uRQoWubzZ0zhbPO+K5gBRsdCI1lLG9Muz/hmApIVXhkFg4ozO8AckWWQGWj7Or
mo59HLDOzwKBgHypQDllIMHLh/3dWvkuJmyLOukQpxmzKBtjaZ74FdaDOGg+jx5A
ndBK3ncmprega+jGNEKD9pzaOT8JRxTHJ4f2G5wyNpe2hBA1gEr9gISuT0HQGq6J
gn1qCVF78f1ItbF7d+fSj2s5nw5XzZOtvEyqek76OQUtASruu/etfbLdAoGAc3p0
LS3R9WvyFnzXKTFW2uOCdwSomvmTmhr59shkkq4eEcWA+ggMZnwN70eXS7ZqIMlp
JKAPgfuC+euzTgoudYD9uc2KqfSxEks0YyaMO0CNSOi0T4zmB5QyUx9Ae1vfibC4
4AJCuhflqURZX6Q10hMfhXPuk/qXujr2GCNpeV8CgYEAwe+USluGIrL9MxK1KZXb
q2RdrCXax7DccNNTQsd2WyTfret/rhmZF/AXo0CRbIWG3F4MaM93OmyafKVCO0v7
lR9NO66zFROQkHxos9gxM5FRJCpZt52X/2SjaZgvKO61y0wJcQXovRbhuWgAlK6f
xTuFTcqNripTmSxrZGWvKB0=
-----END PRIVATE KEY-----"""
client_email = "hybb-utility-service@hybb-utility-system.iam.gserviceaccount.com"
client_id = "109509834810396195524"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hybb-utility-service%40hybb-utility-system.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
